---
- name: create service directories
  file:
    state: directory
    path: "{{ item }}"
    recurse: yes
  with_items:
    - "{{ ansible_unit_test_prefix_dir }}{{ systemd_service_default_dir }}"
    - "{{ ansible_unit_test_prefix_dir }}{{ systemd_service_systemd_dir }}"

- name: write default configuration for service(s)
  template:
    src: default.j2
    dest: "{{ ansible_unit_test_prefix_dir }}/{{ systemd_service_default_dir }}/{{ item.name }}"
  with_items: "{{ systemd_service_units }}"
  notify: reload systemd

- name: adds systemd entry for service(s)
  template:
    src: service.j2
    dest: "{{ ansible_unit_test_prefix_dir }}/{{ systemd_service_systemd_dir }}/{{ item.name }}.service"
  register: service_file
  with_items: "{{ systemd_service_units }}"
  notify: reload systemd

- name: reload systemctl manager configuration
  shell: systemctl daemon-reload
  when: service_file.changed and not ansible_unit_test

- name: Create necessary directories for arbitrary scripts
  file:
    state: directory
    dest: "{{ item.path | dirname }}"
  with_items: "{{ systemd_service_scripts }}"

- name: Drop arbitrary scripts
  copy:
    content: "{{ item.content }}"
    mode: "{{ item.mode|default(0655) }}"
    dest: "{{ item.path }}"
  with_items: "{{ systemd_service_scripts }}"

- name: enable and start services
  service:
    name: "{{ item.name }}"
    state: "{{ item.initial_state|default('started') }}"
    enabled: "{{ item.enabled|default(false) }}"
  with_items: "{{ systemd_service_units }}"
